## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ucmp-performance',
                                 ['point-to-point', 'core', 'network', 'flow-monitor', 'applications', 'internet'])
    obj.source = 'ucmp-performance.cc'